
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import './swiper-bundle.min.css'
import Scripts from "./components/Scripts";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJs Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.2.0/css/line.css" />
        
      </head>
      <body>

        {/* HEADER */}
        <header className="header" id="header">
          <nav className="nav conatiner">
            <a href="#" className="nav_logo">Aayusha</a>
            <div className="nav_menu" id="nav-menu">
              <ul className="nav_list grid">
                <li className="nav_item">
                  < Link href="/" className="nav_link active-link">
                    <i className="uil uil-estate nav_icon"></i>Home
                  </Link>
                </li>

                <li className="nav_item">
                  <Link href="/about" className="nav_link">
                    <i className="uil uil-user nav_icon"></i> About
                  </Link>
                </li>

                <li className="nav_item">
                  <Link href="/skills" className="nav_link">
                    <i className="uil uil-file-alt nav_icon"></i>Skills
                  </Link>
                </li>

                <li className="nav_item">
                  <Link href="/servicess" className="nav_link">
                    <i className="uil uil-briefcase-alt nav_icon"></i>  Services
                  </Link>
                </li>

                <li className="nav_item">
                  <Link href="/portfolio" className="nav_link">
                    <i className="uil uil-scenery nav_icon"></i>Portfolio
                  </Link>
                </li>

                <li className="nav_item">
                  <Link href="/contact" className="nav_link">
                    <i className="uil uil-message nav_icon"></i>ContactMe
                  </Link>
                </li>
              </ul>
              <i className="uil uil-times nav_close" id="nav-close"></i>
            </div>

            <div className="nav_btns">
              <div className="nav_toggle" id="nav-toggle">
                <i className="uil uil-apps"></i>
              </div>
            </div>
          </nav>
        </header>


        {children}
        <Scripts />
        

        {/* FOOTER */}

        <footer className="footer">
        <div className="footer_bg">
            <div className="footer_container container grid">
                <div>
                    <h1 className="footer_title">Aayusha</h1>
                    <span className="footer_subtitle">Backend Developer</span>
                </div>

                <ul className="footer_links">

                    <Link href="/">Home</Link>
                    <li>
                        <Link href="/about" className="footer_link">About</Link>
                    </li>
                    <li>
                        <Link href="/skills" className="footer_link">Skills</Link>
                    </li>
                    <li>
                        <Link href="/servicess" className="footer_link">Services</Link>
                    </li>

                     <li>
                        <Link href="/portfolio" className="footer_link">Portfolio</Link>
                    </li>

                     <li>
                        <Link href="/contact" className="footer_link">Contact Me</Link>
                    </li>

                </ul>

                <div className="footer_socials">
                    <a href="https://www.facebook.com/" target="_blank" className="footer_social">
                        <i className="uil uil-facebook-f"></i>
                    </a>

                    <a href="https://www.instagram.com/" target="_blank" className="footer_social">
                        <i className="uil uil-instagram"></i>
                    </a>

                    <a href="https://www.twitter.com/" target="_blank" className="footer_social">
                        <i className="uil uil-twitter-alt"></i>
                    </a>
                </div>
            </div>
            <p className="footer_copy">&#169; Aayusha. All right reserved.</p>
        </div>
    </footer>
    </body>
    </html>
  )
}
